"""Description of changes

Revision ID: aa0d75c412d2
Revises: c95b919d1818
Create Date: 2025-02-22 01:09:08.974806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0d75c412d2'
down_revision: Union[str, None] = 'c95b919d1818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'device')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('device', sa.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
